name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - flask
  - numpy==1.23.4
  - requests
  - flask
  - flask_cors
  - ipython
  - waitress
  - rq
  - redis
  - requests
  - pygmo
  - pandas
  - matplotlib
  - scipy
  - toml